---
abstract: 'Generate testcases for XML::Parsepp '
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires:
  Test::LongString: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-Parsepp-Testgen
requires:
  Exporter: '0'
  XML::Parser: '0'
  perl: '5.014'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/klaus03/XML-Parsepp-Testgen
  repository: https://github.com/klaus03/XML-Parsepp-Testgen.git
version: '0.03'
